package main

import (
	"fmt"
	"log"
	"os"
	"path/filepath"
	"github.com/gdamore/tcell/v2"
)

var configs struct {
	// Raw strings from config file
	headerText   string
	headerBox    string
	currentDay   string
	passedDays   string
	regularDays  string
	weekDaysName string
	footerColor  string

	// Parsed colors
	headerTextColor    tcell.Color
	headerBoxColor     tcell.Color
	currentDayColor    tcell.Color
	passedDaysColor    tcell.Color
	regularDaysColor   tcell.Color
	weekDaysNameColor  tcell.Color
	footerColorParsed  tcell.Color

	// Other config
	currentDaySymbol string
	emptyCellSymbol  string
	headerBoxWidth   int
	headerBorderX    string
	headerBorderY    string
	headerBorderCLB  string
	headerBorderCLU  string
	headerBorderCRB  string
	headerBorderCRU  string
	showFooter       bool
}

// Layout constants
const (
	calendarWidth = 42
	footerWidth   = 45
	headerY       = 3
	calendarY     = 7
	footerY       = 23
)

var userConfigDir string = getUserConfigDir()
var configDir string = filepath.Join(userConfigDir, "minical")
var configFile string = filepath.Join(configDir, "config")

func getUserConfigDir() string {
	dir, err := os.UserConfigDir()
	if err != nil {
		log.Fatal(err)
	}
	return dir
}

func createConf() string {
	err := os.MkdirAll(configDir, 0755)
	if err != nil {
		log.Fatal(err)
	}

	file, err := os.Create(configFile)
	if err != nil {
		log.Fatal(err)
	}

	defaults := generateText()
	file.Write(defaults)

	return fmt.Sprintf("Default config file was created at %s", configFile)
}

func loadConf() {
	file, err := os.Open(configFile)
	if err != nil {
		log.Fatal(err)
	}
	defer file.Close()

	parse(file)
	parseColors()
}

func ConfExist() {
	_, err := os.Stat(configFile)
	if err == nil {
		loadConf()
	} else {
		createConf()
		loadConf()
	}
}

func parseColors() {
	configs.headerTextColor = mustParseRGB(configs.headerText)
	configs.headerBoxColor = mustParseRGB(configs.headerBox)
	configs.currentDayColor = mustParseRGB(configs.currentDay)
	configs.passedDaysColor = mustParseRGB(configs.passedDays)
	configs.regularDaysColor = mustParseRGB(configs.regularDays)
	configs.weekDaysNameColor = mustParseRGB(configs.weekDaysName)
	configs.footerColorParsed = mustParseRGB(configs.footerColor)
}

func mustParseRGB(s string) tcell.Color {
	var r, g, b int32
	_, err := fmt.Sscanf(s, "%d, %d, %d", &r, &g, &b)
	if err != nil {
		return tcell.ColorWhite
	}
	return tcell.NewRGBColor(r, g, b)
}

func generateText() []byte {
	return []byte(`
# This is the default config generated by the program
# You can manually generate this file by using
# minical --gen-config

# Only rgb colors are supported and has to be in the exact format

headerText = 205, 214, 244
headerBox = 49, 50, 68
currentDay = 137, 220, 235
passedDays = 120, 120, 130
regularDays = 235, 235, 245
weekDaysName = 180, 150, 255

currentDaySymbol = ◆
emptyCellSymbol = ·

headerBoxWidth = 36

headerBorderX = ─
headerBorderY = │
headerBorderCLB = ╰
headerBorderCLU = ╭
headerBorderCRB = ╯
headerBorderCRU = ╮

showFooter = true
footerColor = 160, 160, 180

# If you want to launch this calendar from waybar you can do something like
# "on-click": "kitty -e minical"
# where kitty is your terminal name
	`)
}
